-- =============================================================================
-- AEGIS - Inicialização do Banco de Dados Oracle
-- =============================================================================

-- Tabela de Fichas (Registros de Incidentes)
CREATE TABLE AEGIS_FICHAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ATENDIMENTO_PARA VARCHAR2(100) NOT NULL,
    SERVICO VARCHAR2(100) NOT NULL,
    OFERTA_SERVICO VARCHAR2(100),
    DETALHE_FALHA VARCHAR2(2000),
    CATEGORIA VARCHAR2(100),
    SUBCATEGORIA VARCHAR2(100),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Travas
CREATE TABLE AEGIS_TRAVAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(200) NOT NULL,
    DESCRICAO VARCHAR2(500),
    ENDPOINT VARCHAR2(500) NOT NULL,
    METODO VARCHAR2(10) NOT NULL,
    ATIVO NUMBER(1) DEFAULT 1,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_DESATIVACAO TIMESTAMP
);

-- Tabela de Logs de Execução
CREATE TABLE AEGIS_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ENDPOINT VARCHAR2(500) NOT NULL,
    VALIDATION_NAME VARCHAR2(200),
    RESULT VARCHAR2(2000),
    STATUS VARCHAR2(50) NOT NULL,
    EXECUTION_TIME_MS NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INPUT_VALUE CLOB
);

-- Tabela de Logs de Monitoramento
CREATE TABLE AEGIS_MONITORING_LOGS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR2(200) NOT NULL,
    REQUEST_BODY CLOB,
    DURATION_MS NUMBER DEFAULT 0,
    REMOTE_ADDR VARCHAR2(50),
    USER_AGENT VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para busca
CREATE INDEX IDX_FICHAS_ATENDIMENTO ON AEGIS_FICHAS(ATENDIMENTO_PARA);
CREATE INDEX IDX_FICHAS_SERVICO ON AEGIS_FICHAS(SERVICO);
CREATE INDEX IDX_TRAVAS_NOME ON AEGIS_TRAVAS(NOME);
CREATE INDEX IDX_TRAVAS_ENDPOINT ON AEGIS_TRAVAS(ENDPOINT);
CREATE INDEX IDX_LOGS_STATUS ON AEGIS_LOGS(STATUS);
CREATE INDEX IDX_LOGS_CREATED_AT ON AEGIS_LOGS(CREATED_AT);
CREATE INDEX IDX_MONITORING_SOURCE ON AEGIS_MONITORING_LOGS(SOURCE_SYSTEM);
CREATE INDEX IDX_MONITORING_CREATED_AT ON AEGIS_MONITORING_LOGS(CREATED_AT);

-- Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON AEGIS_FICHAS TO AEGIS;
GRANT SELECT, INSERT, UPDATE, DELETE ON AEGIS_TRAVAS TO AEGIS;
GRANT SELECT ON AEGIS_LOGS TO AEGIS;
GRANT SELECT ON AEGIS_MONITORING_LOGS TO AEGIS;
